### ISSUE TITLE
Applying antialising fix Exception in thread "main" java....

### ISSUE THREAD

**Issue by jwd-analyst** [iihnordic/screamingfrog-docker#2]
I got the following Error:
```
docker run screamingfrog
2022-03-15 15:33:44,842 [main] INFO  - Applying antialising fix
Exception in thread "main" java.lang.UnsupportedOperationException: Unable to open DISPLAY
	at com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:173)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:171)
	at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
	at com.sun.glass.ui.Application.run(Application.java:145)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:258)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:270)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:159)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by jwd-analyst** [comment]
Device: Macbook 
OS: macOS Monterey 
Docker Version: 4.5.0

**Comment by MarkEdmondson1234** [comment]
Did you fix it?
